### ISSUE TITLE
Panic when db is read_only

### ISSUE THREAD

**Issue by onsails** [spacejam/sled#1054]
My application syncs pre-populated sled database from google cloud storage to the instance on task start. It needs sled to be opened in read_only mode to make sure that next time app won't need re-download the whole database. When sled is opened in write mode it modifies database file even if there are no explicit writes from api calls.

When sled is opened in read-only mode it panics:

```
Error: HistoryDB(Sled(Io(Os { code: 22, kind: InvalidInput, message: "Invalid argument" })))
thread 'test_runner' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`: the test returned a termination value with a non-zero status code (1) which indicates a failure', /Users/wb/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/src/libstd/macros.rs:16:9
stack backtrace:
   0:        0x1076ead36 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::ha1596088acaf6a0c
                               at /Users/wb/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/src/libcore/ptr/mod.rs:178
   1:        0x1072ff02e - core::fmt::write::h26bd57c1fd6e9c98
                               at src/libcore/fmt/mod.rs:1069
   2:        0x1076ea449 - std::io::Write::write_fmt::h8325e59be4de2935
                               at /Users/wb/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/src/libcore/ptr/mod.rs:178
   3:        0x1076e9c5a - std::panicking::default_hook::{{closure}}::h6237cd0c14a949d4
                               at /Users/wb/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/src/libcore/ptr/mod.rs:178
   4:        0x1076e8ff5 - std::panicking::rust_panic_with_hook::h8a6abbf97eb52e7a
                               at /Users/wb/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/src/libcore/ptr/mod.rs:178
   5:        0x1076ededa - rust_begin_unwind
                               at /Users/wb/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/src/libcore/ptr/mod.rs:178
   6:        0x1078f7bef - std::panicking::begin_panic_fmt::h8fbd06ff487285fa
   7:        0x107632085 - core::ops::function::FnOnce::call_once::h617eda43e8ee8621
                               at /Users/wb/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/src/libcore/ptr/mod.rs:178
   8:        0x1077298c7 - test::run_test::run_test_inner::{{closure}}::he7bdbbb4f1684ae7
                               at /Users/wb/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/src/libcore/ptr/mod.rs:178
   9:        0x10772d7cb - std::sys_common::backtrace::__rust_begin_short_backtrace::h5a6cabed146633c9
                               at /Users/wb/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/src/libcore/ptr/mod.rs:178
  10:        0x10772d6a6 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h3d8b3a9727cee7b6
                               at /Users/wb/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/src/libcore/ptr/mod.rs:178
  11:        0x107700ffd - std::sys::unix::thread::Thread::new::thread_start::h7d6a16c1ae0a12b4
                               at /Users/wb/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/src/libcore/ptr/mod.rs:178
  12:     0x7fff69026109 - _ZL12preoptimized
test test_runner ... FAILED
```
I've tested it with both rust 1.44 stable and 1.45 nightly. macOS Catallina.
Sled config: 
```rust
Config::new().use_compression(true).read_only(true)
```

**Comment by spacejam** [comment]
Hey @onsails, unfortunately this read_only feature is not implemented in a way that I consider to be worth maintaining. I've removed read_only mode for the next release, and at a later time I will circle back and properly implement it. But for now it is hacky and I don't have time for making read-only work in a correct way for now. But I will return to it in the future.

**Comment by ldobbelsteen** [comment]
Any updates on this? I have a similar use case where I mount databases in a read-only filesystem, but it panics.
