### ISSUE TITLE
SegmentAccountant::initial_segments should not panic on broken recording

### ISSUE THREAD

**Issue by ralfbiedert** [spacejam/sled#1145]
## Background

In an embedded library (written in Rust, consumed by C) we use Sled to store user data. Today we sent some recording via Windows' embedded Archive utility which apparently has trouble compressing the `db` file, which turned out to be 0 bytes.

When trying to load the file anyway, the embedded library crashed the hosting application because of a panic in `segment.rs:522` (sorry for broken stack trace this is as good as I got it):

```
index out of bounds: the len is 0 but the index is 6
thread 'xxx' panicked at 'index out of bounds: the len is 0 but the index is 6', C:Users
b.cargo
egistrysrcgithub.com-1ecc6299db9ec823sled-0.32.1srcpagecachesegment.rs:522:13
stack backtrace:
   0: backtrace::backtrace::trace_unsynchronized
             at C:UsersVssAdministrator.cargo
egistrysrcgithub.com-1ecc6299db9ec82acktrace-0.3.46sracktracemod.rs:66
   1: std::sys_common::backtrace::_print_fmt
             at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54/srclibstdsys_commoacktrace.rs:78
   2: std::sys_common::backtrace::_print::{{impl}}::fmt
             at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54/srclibstdsys_commoacktrace.rs:59
   3: core::fmt::write
             at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54/srclibcoremtmod.rs:1076
   4: std::io::Write::write_fmt<test::helpers::sink::Sink>
             at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54srclibstdiomod.rs:1537
   5: std::io::impls::{{impl}}::write_fmt<Write>
             at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54/srclibstdioimpls.rs:176
   6: std::sys_common::backtrace::_print
             at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54/srclibstdsys_commoacktrace.rs:62
   7: std::sys_common::backtrace::print
             at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54/srclibstdsys_commoacktrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54/srclibstdpanicking.rs:198
   9: std::panicking::default_hook
             at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54/srclibstdpanicking.rs:215
  10: std::panicking::rust_panic_with_hook
             at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54/srclibstdpanicking.rs:486
  11: std::panicking::begin_panic_handler
             at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54/srclibstdpanicking.rs:388
  12: core::panicking::panic_fmt
             at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54/srclibcorepanicking.rs:101
  13: core::panicking::panic_bounds_check
             at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54/srclibcorepanicking.rs:73
  14: core::slice::{{impl}}::index_mut<sled::pagecache::segment::Segment>
             at C:Users
b.rustup	oolchainsstable-x86_64-pc-windows-msvclib
ustlibsrc
ustsrclibcoreslicemod.rs:2878
  15: core::slice::{{impl}}::index_mut<sled::pagecache::segment::Segment,usize>
             at C:Users
b.rustup	oolchainsstable-x86_64-pc-windows-msvclib
ustlibsrc
ustsrclibcoreslicemod.rs:2743
  16: alloc::vec::{{impl}}::index_mut<sled::pagecache::segment::Segment,usize>
             at C:Users
b.rustup	oolchainsstable-x86_64-pc-windows-msvclib
ustlibsrc
ustsrcliballocvec.rs:1954
  17: sled::pagecache::segment::SegmentAccountant::initial_segments
             at C:Users
b.cargo
egistrysrcgithub.com-1ecc6299db9ec823sled-0.32.1srcpagecachesegment.rs:522
  18: sled::pagecache::segment::SegmentAccountant::initialize_from_snapshot
             at C:Users
b.cargo
egistrysrcgithub.com-1ecc6299db9ec823sled-0.32.1srcpagecachesegment.rs:580
  19: sled::pagecache::segment::SegmentAccountant::start
             at C:Users
b.cargo
egistrysrcgithub.com-1ecc6299db9ec823sled-0.32.1srcpagecachesegment.rs:478
  20: sled::pagecache::iobuf::IoBufs::start
             at C:Users
b.cargo
egistrysrcgithub.com-1ecc6299db9ec823sled-0.32.1srcpagecacheiobuf.rs:364
  21: sled::pagecache::logger::Log::start
             at C:Users
b.cargo
egistrysrcgithub.com-1ecc6299db9ec823sled-0.32.1srcpagecachelogger.rs:29
  22: sled::pagecache::PageCache::start
             at C:Users
b.cargo
egistrysrcgithub.com-1ecc6299db9ec823sled-0.32.1srcpagecachemod.rs:648
  23: sled::context::Context::start
             at C:Users
b.cargo
egistrysrcgithub.com-1ecc6299db9ec823sled-0.32.1srccontext.rs:81
  24: sled::db::Db::start_inner
             at C:Users
b.cargo
egistrysrcgithub.com-1ecc6299db9ec823sled-0.32.1srcdb.rs:70
  25: sled::config::Config::open
             at C:Users
```

I know we should catch panics via panic hooks, however, I'm also expecting Sled not to panic on a broken file, but the return an `Err`, the function in question is already `Result<Vec<Segment>>`.

## Bug Report

1. expected result

Opening a broken recording should not panic, but return `Err`.

1. actual result

Panics as above. 

1. sled version

`0.32.1`

1. rustc version

`rustc 1.45.2 (d3fb005a3 2020-07-31)`

1. operating system

Windows 10

1. minimal code sample that helps to reproduce the issue

Unfortunately not allowed to attach recording.

1. logs, panic messages, stack traces

See above.

**Comment by spacejam** [comment]
Thanks for the report! An immediate fix is being worked on in https://github.com/spacejam/sled/pull/1170 and will be released shortly.
