### ISSUE TITLE
Deadlock under high load

### ISSUE THREAD

**Issue by justinlovinger** [spacejam/sled#1412]
I have an application making hundreds of `get` calls and dozens of `insert` calls a second over 8 concurrent threads. Sled consistently deadlocks after several minutes of this. I wasn't able to trigger a deadlock without `insert` calls, but `get` calls themselves did deadlock.

- Sled version `0.34.7`.
- `rustc` version `1.59.0`.
- Linux.

**Comment by Mnwa** [comment]
Hey! I have same problems :( 
Any chance to fix this?

**Comment by dariusc93** [comment]
Since sled is using parking lot, enable their deadlock detection feature and run the small code in a separate thread to detect the deadlock, you could post where it is occurring at.

**Comment by spacejam** [comment]
please post a stacktrace

**Comment by robatipoor** [comment]
I encountered a deadlock problem under high concurrent insertions and removals from the database when using the `flush_async` method. I believe the issue stemmed from the `parking_lot` crate. After updating to version '0.12.1', the problem has been resolved.

**Comment by cloutiertyler** [comment]
We're getting a deadlock on a futex while only doing sequential single-threaded get calls. Reproduces after a few seconds of trying to run our script.

**Comment by cfchou** [comment]
Hello,

> futex(0xffffaa234838, FUTEX_WAIT_PRIVATE, 1, NULL

I'm hitting a seemingly the same problem. Here's the stacktrace

```
(gdb) bt
#0  syscall () at ../sysdeps/unix/sysv/linux/aarch64/syscall.S:38
#1  0x0000aaaaaac5227c in parking_lot_core::thread_parker::imp::ThreadParker::futex_wait (self=0xfffff7feb838, ts=...)
    at /home/chifeng/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/parking_lot_core-0.8.6/src/thread_parker/linux.rs:112
#2  0x0000aaaaaac520dc in parking_lot_core::thread_parker::imp::{impl#0}::park (self=0xfffff7feb838)
    at /home/chifeng/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/parking_lot_core-0.8.6/src/thread_parker/linux.rs:66
#3  0x0000aaaaaac5c3b0 in parking_lot_core::parking_lot::park::{closure#0}<parking_lot::condvar::{impl#1}::wait_until_internal::{closure_env#0}, parking_lot::condvar::{impl#1}::wait_until_internal::{closure_env#1}, parking_lot::condvar::{impl#1}::wait_until_internal::{closure_env#2}> (thread_data=0xfffff7feb818)
    at /home/chifeng/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/parking_lot_core-0.8.6/src/parking_lot.rs:611
#4  0x0000aaaaaac5c084 in parking_lot_core::parking_lot::with_thread_data<parking_lot_core::parking_lot::ParkResult, parking_lot_core::parking_lot::park::{closure_env#0}<parking_lot::condvar::{impl#1}::wait_until_internal::{closure_env#0}, parking_lot::condvar::{impl#1}::wait_until_internal::{closure_env#1}, parking_lot::condvar::{impl#1}::wait_until_internal::{closure_env#2}>> (f=...) at /home/chifeng/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/parking_lot_core-0.8.6/src/parking_lot.rs:183
#5  parking_lot_core::parking_lot::park<parking_lot::condvar::{impl#1}::wait_until_internal::{closure_env#0}, parking_lot::condvar::{impl#1}::wait_until_internal::{closure_env#1}, parking_lot::condvar::{impl#1}::wait_until_internal::{closure_env#2}> (key=187649993679056, validate=..., before_sleep=..., timed_out=..., park_token=..., timeout=...)
    at /home/chifeng/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/parking_lot_core-0.8.6/src/parking_lot.rs:576
#6  0x0000aaaaaac55bc4 in parking_lot::condvar::Condvar::wait_until_internal (self=0xaaaaab3720d0, mutex=0xaaaaab371fe8, timeout=...) at src/condvar.rs:338
#7  0x0000aaaaaab2acac in parking_lot::condvar::Condvar::wait<sled::pagecache::iobuf::StabilityIntervals> (self=0xaaaaab3720d0, mutex_guard=0xffffffffa438)
    at /home/chifeng/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/parking_lot-0.11.2/src/condvar.rs:260
#8  0x0000aaaaaabd98fc in sled::pagecache::iobuf::make_stable_inner (iobufs=0xaaaaab372f10, lsn=65044, partial_durability=false) at src/pagecache/iobuf.rs:997
#9  0x0000aaaaaabd8fa0 in sled::pagecache::iobuf::make_stable (iobufs=0xaaaaab372f10, lsn=65044) at src/pagecache/iobuf.rs:881
#10 0x0000aaaaaabd9a6c in sled::pagecache::iobuf::flush (iobufs=0xaaaaab372f10) at src/pagecache/iobuf.rs:1014
#11 0x0000aaaaaabe69dc in sled::pagecache::logger::Log::flush (self=0xaaaaab372f00) at src/pagecache/logger.rs:37
#12 0x0000aaaaaab60ce0 in sled::pagecache::PageCache::flush (self=0xaaaaab372eb8) at src/pagecache/mod.rs:762
#13 0x0000aaaaaab892d0 in sled::tree::{impl#2}::drop (self=0xaaaaab36c588) at src/tree.rs:103
#14 0x0000aaaaaabbfeb0 in core::ptr::drop_in_place<sled::tree::TreeInner> () at /rustc/17067e9ac6d7ecb70e50f92c1944e545188d2359/library/core/src/ptr/mod.rs:523
#15 0x0000aaaaaabc2a24 in core::ptr::drop_in_place<sled::arc::ArcInner<sled::tree::TreeInner>> () at /rustc/17067e9ac6d7ecb70e50f92c1944e545188d2359/library/core/src/ptr/mod.rs:523
#16 0x0000aaaaaabc3f5c in core::ptr::drop_in_place<alloc::boxed::Box<sled::arc::ArcInner<sled::tree::TreeInner>, alloc::alloc::Global>> ()
    at /rustc/17067e9ac6d7ecb70e50f92c1944e545188d2359/library/core/src/ptr/mod.rs:523
#17 0x0000aaaaaabd2a00 in sled::arc::{impl#8}::drop<sled::tree::TreeInner> (self=0xffffffffe2b8) at src/arc.rs:156
#18 0x0000aaaaaabc2358 in core::ptr::drop_in_place<sled::arc::Arc<sled::tree::TreeInner>> () at /rustc/17067e9ac6d7ecb70e50f92c1944e545188d2359/library/core/src/ptr/mod.rs:523
#19 0x0000aaaaaabbfb04 in core::ptr::drop_in_place<sled::tree::Tree> () at /rustc/17067e9ac6d7ecb70e50f92c1944e545188d2359/library/core/src/ptr/mod.rs:523
#20 0x0000aaaaaabbf79c in core::ptr::drop_in_place<sled::db::Db> () at /rustc/17067e9ac6d7ecb70e50f92c1944e545188d2359/library/core/src/ptr/mod.rs:523
#21 0x0000aaaaaab0b2a0 in sled_writes::engine_write (c=0xffffffffe3c8) at src/bin/sled_writes.rs:93
#22 0x0000aaaaaab0b35c in sled_writes::benches () at src/bin/sled_writes.rs:98
#23 0x0000aaaaaab0b3b8 in sled_writes::main () at src/bin/sled_writes.rs:102
(gdb)
```

My benchmark(using criterion) writes keys and values of length 1~100_000.


```rust
use std::io;
use criterion::Criterion;
use tracing_subscriber::EnvFilter;
use rand::{Rng, SeedableRng};
use rand::distr::Alphanumeric;
use tempfile::TempDir;
use tracing::{debug, info, trace};
use sled;

const SAMPLE_SIZE: usize = 30;
const MAX_LENGTH: u32 = 100_000;


fn input_setup(seed: u64) -> (String, String) {
    // generate random keys and values of length 1~MAX_LENGTH bytes.
    let mut rng = rand::rngs::SmallRng::seed_from_u64(seed);
    let ln = rng.random_range(1..=MAX_LENGTH) as usize;

    debug!(seed, ln, "fill>>");
    let key = rng.sample_iter(&Alphanumeric)
        .take(ln)
        .map(char::from)
        .collect::<String>();
    let value = key.clone();
    debug!(ln, "filled<<");
    (key, value)
}

fn engine_write(c: &mut Criterion) {
    tracing_subscriber::fmt()
        .with_env_filter(EnvFilter::from_default_env())
        // by default stdout
        .with_writer(io::stderr)
        .with_target(false)
        .with_file(true)
        .with_line_number(true)
        .with_thread_ids(true)
        .compact()
        .init();

    let mut seed: u64 = 0;
    let tree = sled::open(
        TempDir::new().unwrap().path()
    ).unwrap();
    c.bench_function(
        "sled_writes",
        |bencher| {
            bencher.iter_batched(
                || {
                    let data = input_setup(seed);
                    let ln = data.0.len();
                    debug!(seed, ln, "setup");
                    seed += 1;
                    data
                },
                |mut setup| {
                    let ln = setup.0.len();
                    debug!(ln, "set=======================>");
                    let value = sled::IVec::from(setup.1.as_str());
                    tree.insert(&setup.0, value).unwrap();
                },
                criterion::BatchSize::SmallInput,
            )
        }
    );
}

pub fn benches() {
    let mut criterion = (Criterion::default().sample_size(SAMPLE_SIZE))
        .configure_from_args();
    engine_write(&mut criterion);
}

fn main() {
    benches();

    info!("done==================");
    // Criterion::default()
    //     .configure_from_args()
    //     .final_summary();
}

```

**Comment by cfchou** [comment]
Actually the problem is to do with TempDir being removed when sled tries to write.

Replace 
```
    let tree = sled::open(
        TempDir::new().unwrap().path()
    ).unwrap();
```
to non-temp dir fixed my issue.
