### ISSUE TITLE
cyclical linearizability bug: PageCache::pull read invalid data at lid 66244182

### ISSUE THREAD

**Issue by spacejam** [spacejam/sled#182]

**Comment by spacejam** [comment]
```
thread 'main' panicked at 'read invalid data at lid 7473086: Ok(Zeroed(63530))', src/io/page_cache.rs:868:21                                                                                  
stack backtrace:                                                                                                                                                                              
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:69
   2: std::panicking::default_hook::{{closure}}                                                                                                                                               
             at /checkout/src/libstd/sys_common/backtrace.rs:58                                                                                                                               
             at /checkout/src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:397
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:577
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:538
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:522
   7: <sled::io::page_cache::PageCache<PM, P, R>>::page_in                                                                                                                                    
             at src/io/page_cache.rs:868                                                                                                                                                      
             at src/io/page_cache.rs:689
   8: <sled::tree::iter::Iter<'a> as core::iter::iterator::Iterator>::next
             at src/io/page_cache.rs:619
             at src/tree/iter.rs:20
   9: cyclical_linearizability::main
             at src/bin/cyclical_linearizability.rs:21
             at src/bin/cyclical_linearizability.rs:89
```
