### ISSUE TITLE
failpoints test does not clean up after itself properly

### ISSUE THREAD

**Issue by spacejam** [spacejam/sled#280]
```
---- quickcheck_tree_with_failpoints stdout ----
	thread 'quickcheck_tree_with_failpoints' panicked at 'duplicate segment LSN detected, one should have been zeroed out during recovery', crates/pagecache/src/io/segment.rs:1054:13
note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread 'quickcheck_tree_with_failpoints' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', /checkout/src/libcore/result.rs:916:5
thread 'quickcheck_tree_with_failpoints' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', /checkout/src/libcore/result.rs:916:5
thread 'quickcheck_tree_with_failpoints' panicked at '[quickcheck] TEST FAILED (runtime error). Arguments: ([], false)
Error: "called `Result::unwrap()` on an `Err` value: \"PoisonError { inner: .. }\""', /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/quickcheck-0.6.1/src/tester.rs:179:28
```

I don't believe this is an issue with the pagecache itself, but rather with a test that is not cleaned up properly, and shrinking the operation set to `[]` continues causing the issue. There is another bug that triggers the initial test to fail, that has not yet been revealed.

**Comment by spacejam** [comment]
Set, Set, Set, FailPoint("trailer write"), Set, Set, Del(0), Set
