### ISSUE TITLE
possible segment optimistic rewrite bug

### ISSUE THREAD

**Issue by spacejam** [spacejam/sled#967]
this happened after messing with Arc<IoBuf> stuff in #964 so it might not be a current bug but I'm flagging it here for extra testing before 0.31.1 gets released.

```rust
benchmarks/stress2 [tyler_dynamic_concurrency_control ●]
λ cargo flamegraph --features=no_metrics -- --total-ops=100000000 --entries=10240 --get-prop=1000000000 --threads=12 --key-len=4
   Compiling sled v0.31.0 (/home/t/src/sled)
   Compiling stress2 v0.1.0 (/home/t/src/sled/benchmarks/stress2)
    Finished release [optimized + debuginfo] target(s) in 34.32s
thread 'main' panicked at 'load_snapshot pid 9521 not found, despite being below the max pid 5880730', /home/t/src/sled/src/pagecache/mod.rs:1855:17
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:84
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1025
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:193
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:210
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:471
  11: rust_begin_unwind
             at src/libstd/panicking.rs:375
  12: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:326
  13: sled::pagecache::PageCache::load_snapshot
             at /home/t/src/sled/src/pagecache/mod.rs:1855
  14: sled::pagecache::PageCache::start
             at /home/t/src/sled/src/pagecache/mod.rs:557
  15: sled::context::Context::start
             at /home/t/src/sled/src/context.rs:52
  16: sled::db::Db::start_inner
             at /home/t/src/sled/src/db.rs:79
  17: sled::config::Config::open
             at /home/t/src/sled/src/config.rs:364
  18: stress2::main
             at src/main.rs:231
```

**Comment by spacejam** [comment]
fixed in #1041
